#!/bin/sh

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for file in /etc/X11/xinit/xinitrc.d/*; do
    [ -x $file ] && . $file
  done
  unset file
fi

xsetroot -cursor_name arrow &
$HOME/.config/herbstluftwm/panel.sh &
setxkbmap -layout de -option ctrl:swapcaps -variant nodeadkeys &
# -option compose:alt
xmodmap -e "keysym Caps_Lock = NoSymbol" &
xcape -e 'Control_L=Escape' &
redshift -l 51.43072:7.16941 &> /dev/null &
hsetroot -full "$( find $HOME/pictures/wallpaper/1920x1080 -type f | shuf -n 1 )" &
sxhkd -c ${HOME}/.config/sxhkd/sxhkdrc &
unclutter &
mpd &
dunst &
xautolock -time 15 -locker slock &
xrandr --setprovideroffloadsink 0x55 0x7e

session=${1:-hlwm}
case $session in
    hlwm )
		exec herbstluftwm -c "${HOME}/.config/herbstluftwm/autostart" --locked
	;;
    cwm )
		exec cwm -c "${HOME}/.config/cwm/cwmrc"
	;;
    bspwm )
		exec bspwm -c "${HOME}/.config/bspwm/bspwmrc"
	;;
    * )
		exec $1
	;;
esac
