#!/bin/sh

if [ -d /etc/X11/xinit/xinitrc.d ]; then
    for f in /etc/X11/xinit/xinitrc.d/*; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

exec i3 &
exec xrdb -load $HOME/.config/X11/Xresources &
exec xsetroot -cursor_name arrow &
exec xset +fp /usr/share/fonts/local &
exec xset fp rehash &
exec sxhkd &
exec setxkbmap -option compose:rctrl &
exec xautolock -time 10 -locker $HOME/.bin/lock-screen -detectsleep &

exec crond &
exec udiskie &
exec xcmenu &
exec compton &
exec light 20% &
exec unclutter &
exec $HOME/.bin/random-wallpaper &
exec $HOME/.bin/lightson &
exec urxvtd &
exec dunst
