#!/bin/sh

if [ -d /etc/X11/xinit/xinitrc.d ]; then
    for f in /etc/X11/xinit/xinitrc.d/*; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

# Load the Xresources-File
xrdb -load $HOME/.config/X11/Xresources &

# Set the arrow curser as the default cursor
xsetroot -cursor_name arrow &

# Fixing Font-Caching
xset +fp /usr/share/fonts/local &
xset fp rehash &

# Set the R_Ctrl as the compose-key
setxkbmap -option compose:rctrl &

# Screenlocker
xautolock -time 10 -locker $HOME/.bin/lock-screen -detectsleep &

# Udiskie, to automount devices
udiskie &

# A nice little Clipboar-Manager
xcmenu &

# My compositer
compton -b &

# Set the background-light to 30%
light 30% &

# Hide the cursor after some time
unclutter &

# Set a random wallpaper
$HOME/.bin/random-wallpaper &

# Stop the screenlocker, when seeing Movies via Flash
$HOME/.bin/lightson &

# Starting the urxvt-daemon
urxvtd &

# My keybindings-daemon
sxhkd &

# Panel
~/.config/bspwm/panel dzen2 &

# Notifier
dunst &

# Powersaving
powerdown &

# Starting the JACK Daemon
$HOME/.bin/start-jack &

# Starting a window manager
session=${1:-hlwm}
case $session in
    xmonad  )       exec xmonad;;
    bspwm   )       exec bspwm;;
    i3      )       exec i3;;
    2bwm    )       exec 2bwm;;
    hlwm    )       exec herbstluftwm --locked;;
    *       )       exec $1;;
esac
