#!/bin/sh

bspc config border_width 3
bspc config window_gap 10

bspc config normal_border_color "#cccccc"
bspc config focused_border_color "#ff0055"
bspc config active_border_color "#ff0055"

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_by_distance true

bspc monitor -d I II III IV V VI VII VIII IX X
