#!/bin/sh

i=1
for monitor in $(bspc query -M); do
bspc monitor $monitor \
        -n "$i" \
        -d $i/{i,ii,iii,iv,v,vi,vii,viii,ix,x}
    let i++
done
NMON=$i
unset i

bspc config top_padding 30

# Visual options
bspc config split_ratio         0.50
bspc config border_width        5
bspc config window_gap          15
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_follows_pointer true
bspc config auto_alternate true
bspc config auto_cancel true
bspc config normal_border_color "#303030"
bspc config active_border_color "#303030"
bspc config focused_border_color "#FF0055"
bspc config presel_border_color "#303030"
bspc config urgent_border_color "#005F87"
bspc config focused_locked_border_color "#FF4000"
bspc config normal_frame_opacity 0.0
bspc config focused_frame_opacity 0.1

# Rules
bspc rule -a Conky sticky=on manage=off lower=on
# bspc rule -a bar floating=on manage=off
