# apple2
# Autogenerated from man page /usr/share/man/man6/apple2.6.gz
# using Deroffing man parser
complete -c apple2 -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c apple2 -o root --description 'Draw on the root window.'
complete -c apple2 -o mono --description 'If on a color display, pretend we\'re on a monochrome display.'
complete -c apple2 -o install --description 'Install a private colormap for the window.'
complete -c apple2 -o visual --description 'Specify which visual to use.'
complete -c apple2 -o basic --description 'Choose basic mode.'
complete -c apple2 -o slideshow --description 'Choose slideshow mode.'
complete -c apple2 -o text --description 'Choose text mode.'
complete -c apple2 -o program --description 'In text mode, the command to run to generate th… [See Man Page]'
complete -c apple2 -o pty --description 'In -text mode, launch the sub-program under a p… [See Man Page]'
complete -c apple2 -o pipe --description 'In -text mode, launch the sub-program at the en… [See Man Page]'
complete -c apple2 -o esc --description 'When the user types a key with the Alt or Meta … [See Man Page]'
complete -c apple2 -o meta --description 'When Meta or Alt are held down, set the high bi… [See Man Page]'
complete -c apple2 -o del --description 'Swap Backspace and Delete.   This is the default.'
complete -c apple2 -o bs --description 'Do not swap Backspace and Delete.'
complete -c apple2 -o fast --description 'Normally, characters are printed at the speed o… [See Man Page]'
complete -c apple2 -o fps --description 'Display the current frame rate and CPU load.'

