# autogsdoc
# Autogenerated from man page /usr/share/man/man1/autogsdoc.1.gz
# using Deroffing man parser
complete -c autogsdoc -o Projects --description 'MacrosTemplate 4 Specify the name of a template… [See Man Page]'

