# bsod
# Autogenerated from man page /usr/share/man/man6/bsod.6.gz
# using Deroffing man parser
complete -c bsod -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c bsod -o root --description 'Draw on the root window.'
complete -c bsod -o mono --description 'If on a color display, pretend we\'re on a monochrome display.'
complete -c bsod -o install --description 'Install a private colormap for the window.'
complete -c bsod -o visual --description 'Specify which visual to use.'
complete -c bsod -o delay --description 'The duration each crash-mode is displayed befor… [See Man Page]'
complete -c bsod -o only --description 'Tell it to run only one mode, e. g. , -only HPUX.'
complete -c bsod -o fps --description 'Display the current frame rate and CPU load.'

