# cd-discid
# Autogenerated from man page /usr/share/man/man1/cd-discid.1.gz
# using Deroffing man parser
complete -c cd-discid -l musicbrainz --description 'Output a TOC that is suitable for calculating t… [See Man Page]'
complete -c cd-discid -l help --description 'Display a brief help message.'
complete -c cd-discid -l version --description 'Show the version.'

