# cgdb
# Autogenerated from man page /usr/share/man/man1/cgdb.1.gz
# using Deroffing man parser
complete -c cgdb -l version --description 'Print version information and then exit.'
complete -c cgdb -l help --description 'Print help (this message) and then exit.'
complete -c cgdb -s d --description 'Set debugger to use.'

