# cower
# Autogenerated from man page /usr/share/man/man1/cower.1.gz
# using Type1
complete -c cower -s b -l brief --description 'Show output in a more script friendly format.'
complete -c cower -s c -l 'color[' --description 'Use colored output.  \\s-1WHEN\\s0 is never, always or auto.'
complete -c cower -l debug --description 'Show debug output.  This option should be passed first if used.'
complete -c cower -s f -l force --description 'Overwrite existing files when downloading.'
complete -c cower -l format --description 'Print outside from --info, --search, and --msea… [See Man Page]'
complete -c cower -s h -l help --description 'Display the help message and quit.'
complete -c cower -l ignore --description 'Ignore a package upgrade.  Can be used more than once.'
complete -c cower -l 'ignorerepo[' --description 'Ignore a binary repo when checking for updates.'
complete -c cower -l listdelim --description 'Specify a delimiter when printing list formatte… [See Man Page]'
complete -c cower -l no-ignore-ood --description 'The reverse of --ignore-ood.'
complete -c cower -s o -l ignore-ood --description 'Ignore all results marked as out of date.'
complete -c cower -l sort -l rsort --description 'Sort the results in ascending or descending ord… [See Man Page]'
complete -c cower -s p -l from-pkgbuild --description 'Interpret non-option arguments to cower as path… [See Man Page]'
complete -c cower -s q -l quiet --description 'Output less.'
complete -c cower -s t -l target --description 'Download targets to alternate directory, specif… [See Man Page]'
complete -c cower -l threads --description 'Limit the number of threads created, with a default of 10.'
complete -c cower -l timeout --description 'Specify how long libcurl is willing to wait for… [See Man Page]'
complete -c cower -s v -l verbose --description 'Output more.  This primarily affects the update operation.'

