# crond
# Autogenerated from man page /usr/share/man/man8/crond.8.gz
# using Deroffing man parser
complete -c crond -s s --description 'directory of system crontabs (defaults to /etc/cron. d) . RS .'
complete -c crond -s c --description 'directory of per-user crontabs (defaults to /va… [See Man Page]'
complete -c crond -s t --description 'directory of timestamps for \\@freq and FREQ=.'
complete -c crond -s m --description 'where should the output of cronjobs be directed… [See Man Page]'
complete -c crond -s M --description 'Any output that cronjobs print to stdout or std… [See Man Page]'
complete -c crond -s S --description 'log events to syslog, using syslog facility LOG… [See Man Page]'
complete -c crond -s L --description 'log to specified file instead of syslog. RS . RE.'
complete -c crond -s l --description 'log events at the specified, or more important, loglevels.'
complete -c crond -s b --description 'run \\f[B]crond\\f[] in the background (default u… [See Man Page]'
complete -c crond -s f --description 'run \\f[B]crond\\f[] in the foreground.'
complete -c crond -s d --description 'turn on debugging.'

