# cspctl
# Autogenerated from man page /usr/share/man/man1/cspctl.1.gz
# using Deroffing man parser
complete -c cspctl -s h -l help --description 'Display a short help.'
complete -c cspctl -s c --description 'Select a card number.  Option defaults to 0.'
complete -c cspctl -s f --description 'Select a function from microcode file.  Option defaults to 1.'
complete -c cspctl -s d --description 'Optional microcode description string.'

