# cvtenc
# Autogenerated from man page /usr/share/man/man1/cvtenc.1.gz
# using Deroffing man parser
complete -c cvtenc -o Encoding --description 'Specify non-unicode encoding to be used.'
complete -c cvtenc -o EscapeIn --description 'Specify \'-EscapeIn YES\' (the default is \'NO\') t… [See Man Page]'
complete -c cvtenc -o EscapeOut --description 'Specify \'-EscapeOut YES\' (the default is \'NO\') … [See Man Page]'
complete -c cvtenc -o Unicode --description 'Specify \'-Unicode IN\' (or \'-Unicode OUT\') to co… [See Man Page]'

