# cynosure
# Autogenerated from man page /usr/share/man/man6/cynosure.6.gz
# using Deroffing man parser
complete -c cynosure -o visual --description 'Specify which visual to use.'
complete -c cynosure -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c cynosure -o root --description 'Draw on the root window.'
complete -c cynosure -o delay --description 'Per-frame delay, in microseconds.   Default: 500000 (0.'
complete -c cynosure -o ncolors --description 'Number of Colors.   Default: 128.'
complete -c cynosure -o iterations --description 'Duration.   2 - 200.   Default: 100.'
complete -c cynosure -o fps --description 'Display the current frame rate and CPU load.'

