# dvdbackup
# Autogenerated from man page /usr/share/man/man1/dvdbackup.1.gz
# using Deroffing man parser
complete -c dvdbackup -s h -l help --description 'print a brief usage message.'
complete -c dvdbackup -s V -l version --description 'print version information.'
complete -c dvdbackup -s I -l info --description 'for information about the DVD.'
complete -c dvdbackup -s M -l mirror --description 'backup the whole DVD.'
complete -c dvdbackup -s F -l feature --description 'backup the main feature of the DVD.'
complete -c dvdbackup -s T -l titleset --description 'backup title set X.'
complete -c dvdbackup -s t -l title --description 'backup title X.'
complete -c dvdbackup -s s -l start --description 'backup from chapter X.'
complete -c dvdbackup -s e -l end --description 'backup to chapter X.'
complete -c dvdbackup -s i -l input --description 'where DEVICE is your DVD device.'
complete -c dvdbackup -s o -l output --description 'where DIRECTORY is your backup target.'
complete -c dvdbackup -s v -l verbose --description 'print more information about progress.'
complete -c dvdbackup -s n -l name --description '(optional) set the title - useful if autodetection fails.'
complete -c dvdbackup -s a -l aspect --description 'to get aspect ratio 4:3 instead of 16:9 if both are present.'
complete -c dvdbackup -s r -l error --description 'select read error handling: a=abort, b=skip blo… [See Man Page]'
complete -c dvdbackup -s p -l progress --description 'print progress information while copying VOBs Option notes.'
complete -c dvdbackup -s 1 --description 'on failure AUTHORS dvdbackup was written by Ola… [See Man Page]'

