# dwb
# Autogenerated from man page /usr/share/man/man1/dwb.1.gz
# using Deroffing man parser
complete -c dwb -s c -l check-script-syntax --description 'Checks if a the syntax of a script that uses th… [See Man Page]'
complete -c dwb -s d -l delete-profile --description 'Deletes a profile.'
complete -c dwb -s e -l embed --description 'Embed dwb into <wid>.'
complete -c dwb -s f -l force --description 'Force restoring a previously saved session, eve… [See Man Page]'
complete -c dwb -l fifo --description 'Use a fifo for single instance instead of dbus,… [See Man Page]'
complete -c dwb -s l -l list-sessions --description 'List previously saved sessions.'
complete -c dwb -s n -l new-instance --description 'New instance, overrides setting single-instance.'
complete -c dwb -s p -l profile --description 'Load configuration for profile profilename.'
complete -c dwb -s r -l restore --description 'Restore session with name sessionname or the de… [See Man Page]'
complete -c dwb -s R -l override-restore --description 'Open a new session, even if save-session is enabled.'
complete -c dwb -s S -l enable-scripts --description 'Enables the javascript interface, if there are … [See Man Page]'
complete -c dwb -l set-as-default --description 'Sets dwb as default browser, if called with no … [See Man Page]'
complete -c dwb -s t -l temp-profile --description 'Create a temporary profile, will be deleted when dwb is closed.'
complete -c dwb -s x -l execute --description 'Execute a list of dwb commands separated by ;;,… [See Man Page]'
complete -c dwb -s v -l version --description 'Show version information and exit.'
complete -c dwb -s V -l version-full --description 'Show full version information, including librar… [See Man Page]'
complete -c dwb -o 'n.' --description 'true.  ssl-strict.'

