# dwbremote
# Autogenerated from man page /usr/share/man/man1/dwbremote.1.gz
# using Deroffing man parser
complete -c dwbremote -s a -l all --description 'Sends a command to all windows.'
complete -c dwbremote -s c -l class --description 'Search for window id by WM_CLASS.'
complete -c dwbremote -s i -l id --description 'Send comands to window with id window_id, windo… [See Man Page]'
complete -c dwbremote -s l -l list --description 'List all dwb window ids with enabled ipc.'
complete -c dwbremote -s n -l name --description 'Search for window id by WM_NAME.'
complete -c dwbremote -s p -l pid --description 'Search for window id by process id pid.'
complete -c dwbremote -s s -l show-id --description 'Print the window id in every response, the wind… [See Man Page]'

