# fontglide
# Autogenerated from man page /usr/share/man/man6/fontglide.6.gz
# using Deroffing man parser
complete -c fontglide -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c fontglide -o root --description 'Draw on the root window.'
complete -c fontglide -o install --description 'Install a private colormap for the window.'
complete -c fontglide -o visual --description 'Specify which visual to use.'
complete -c fontglide -o delay --description 'The delay between steps of the animation, in mi… [See Man Page]'
complete -c fontglide -o page --description 'With this option, a page full of text will glid… [See Man Page]'
complete -c fontglide -o scroll --description 'With this option, sentences will scroll by from right to left.'
complete -c fontglide -o random --description 'The default is to pick randomly between -page and  -scroll.'
complete -c fontglide -o speed --description 'How fast to animate; 2 means twice as fast, 0.'
complete -c fontglide -o linger --description 'How long to leave the assembled text on the scr… [See Man Page]'
complete -c fontglide -o program --description 'The command to run to generate the text to display.'
complete -c fontglide -o font --description 'The base font pattern to use when loading fonts.'
complete -c fontglide -o bw --description 'How thick an outline to draw around the characters.'
complete -c fontglide -o trails --description 'Leave "vapor trails" behind the moving text.   Default off.'
complete -c fontglide -o no-db --description 'Turn off double-buffering.'
complete -c fontglide -o debug --description 'Draw some boxes showing character metrics, and … [See Man Page]'
complete -c fontglide -o fps --description 'Display the current frame rate and CPU load.'

