# gdnc
# Autogenerated from man page /usr/share/man/man1/gdnc.1.gz
# using Deroffing man parser
complete -c gdnc -o NSHost --description 'argument.'
complete -c gdnc -o GSPublic --description 'P To run a copy of the server to handle network… [See Man Page]'
complete -c gdnc -o GSNetwork --description '.'

