# gdomap
# Autogenerated from man page /usr/share/man/man8/gdomap.8.gz
# using Deroffing man parser
complete -c gdomap -s C --description 'help about configuration.'
complete -c gdomap -s H --description 'general help.'
complete -c gdomap -s I --description 'pid file to write pid.'
complete -c gdomap -s L --description 'perform lookup for name then quit.'
complete -c gdomap -s M --description 'machine name for   -L and   -N.'
complete -c gdomap -s N --description 'list all names registered on host.'
complete -c gdomap -s P --description 'port number required for   -R  option.'
complete -c gdomap -s R --description 'register name locally then quit.'
complete -c gdomap -s T --description 'port type for   -L ,  -R and  -U  options - tcp… [See Man Page]'
complete -c gdomap -s U --description 'unregister name locally then quit.'
complete -c gdomap -s a --description 'use config file for interface list.'
complete -c gdomap -s c --description 'use config file for probe.'
complete -c gdomap -s d --description 'extra debug logging (normally via syslog).'
complete -c gdomap -s f --description 'avoid fork() to make debugging easy.'
complete -c gdomap -s i --description 're-probe at this interval (roughly), min 60.'
complete -c gdomap -s p --description 'disable probing for other servers.'

