# glade-previewer
# Autogenerated from man page /usr/share/man/man1/glade-previewer.1.gz
# using Deroffing man parser
complete -c glade-previewer -s f -l filename --description 'Name of the file to preview.'
complete -c glade-previewer -s t -l toplevel --description 'Name of the toplevel to preview.'
complete -c glade-previewer -s l -l listen --description 'Listen on standard input.'
complete -c glade-previewer -s v -l version --description 'Output version information and exit.'
complete -c glade-previewer -l display --description 'X display to use.'

