# glade
# Autogenerated from man page /usr/share/man/man1/glade.1.gz
# using Deroffing man parser
complete -c glade -s h -l help --description 'Show help options.'
complete -c glade -l help-all --description 'Show all help options.'
complete -c glade -l help-debug --description 'Show Glade debug options.'
complete -c glade -l help-gtk --description 'Show GTK+ options.'
complete -c glade -l version --description 'Output version information and exit.'
complete -c glade -l without-devhelp --description 'Disable devhelp integration.'
complete -c glade -l display --description 'X display to use.'

