# gnustep-config
# Autogenerated from man page /usr/share/man/man1/gnustep-config.1.gz
# using Deroffing man parser
complete -c gnustep-config -l variable --description 'prints the value of the specified variable.'
complete -c gnustep-config -l objc-flags --description 'prints all the flags required to compile an ObjC file.'
complete -c gnustep-config -l objc-libs --description 'prints all the flags required to link a pure Ob… [See Man Page]'
complete -c gnustep-config -l base-libs --description 'prints all the flags required to link a command… [See Man Page]'
complete -c gnustep-config -l gui-libs --description 'prints all the flags required to link a GUI ObjC program.'

