# goop
# Autogenerated from man page /usr/share/man/man6/goop.6.gz
# using Deroffing man parser
complete -c goop -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c goop -o root --description 'Draw on the root window.'
complete -c goop -o mono --description 'If on a color display, pretend we\'re on a monochrome display.'
complete -c goop -o install --description 'Install a private colormap for the window.'
complete -c goop -o visual --description 'Specify which visual to use.'
complete -c goop -o count --description 'How many bubbles to draw per layer.   Default: random.'
complete -c goop -o planes --description 'How many planes to draw.'
complete -c goop -o delay --description 'How much of a delay should be introduced betwee… [See Man Page]'
complete -c goop -o transparent --description 'If -layers is greater than 1, then each layer w… [See Man Page]'
complete -c goop -o non-transparent --description 'Turns off -transparent.'
complete -c goop -o additive --description 'If -transparent is specified, then this option … [See Man Page]'
complete -c goop -o subtractive --description 'If -transparent is specified, then this option … [See Man Page]'
complete -c goop -o xor --description 'Draw with xor instead of the other color tricks.'
complete -c goop -o fps --description 'Display the current frame rate and CPU load.'

