# granola
# Autogenerated from man page /usr/share/man/man8/granola.8.gz
# using Deroffing man parser
complete -c granola -s D --description 'Daemonize the Granola process.'
complete -c granola -s c --description 'Use FILE as the configuration file for Granola.'
complete -c granola -s d --description 'Enable debug output to syslog and the terminal.'
complete -c granola -s h --description 'Print this help and exit.'
complete -c granola -s v --description 'Print version information and exit.'

