# hciconfig
# Autogenerated from man page /usr/share/man/man1/hciconfig.1.gz
# using Deroffing man parser
complete -c hciconfig -s h -l help --description 'Gives a list of possible commands.'
complete -c hciconfig -s a -l all --description 'Other than the basic info, print features, pack… [See Man Page]'

