# helix
# Autogenerated from man page /usr/share/man/man6/helix.6.gz
# using Deroffing man parser
complete -c helix -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c helix -o root --description 'Draw on the root window.'
complete -c helix -o mono --description 'If on a color display, pretend we\'re on a monochrome display.'
complete -c helix -o delay --description 'This sets the number of seconds that the helix … [See Man Page]'
complete -c helix -o subdelay --description 'This sets the amount of time to pause periodica… [See Man Page]'
complete -c helix -o install --description 'Install a private colormap for the window.'
complete -c helix -o visual --description 'Specify which visual to use.'
complete -c helix -o fps --description 'Display the current frame rate and CPU load.'

