# hexcurse
# Autogenerated from man page /usr/share/man/man1/hexcurse.1.gz
# using Deroffing man parser
complete -c hexcurse -s '?' -o help --description 'Prints out the command usage info.'
complete -c hexcurse -s a --description 'Specifies the addresses to be output in decimal… [See Man Page]'
complete -c hexcurse -s r --description 'Specifies the number of characters per line tha… [See Man Page]'
complete -c hexcurse -s o --description 'Specifies the output file to be written to by default.'
complete -c hexcurse -s i --description 'is not needed if inputfile is the last argument on the line.'

