# i8kbuttons
# Autogenerated from man page /usr/share/man/man1/i8kbuttons.1.gz
# using Type1
complete -c i8kbuttons -s v -l verbose --description 'Verbose mode, show all commands executed.'
complete -c i8kbuttons -s u -l up --description 'Specifies the command to be executed when the V… [See Man Page]'
complete -c i8kbuttons -s d -l down --description 'Specifies the command to be executed when the V… [See Man Page]'
complete -c i8kbuttons -s m -l mute --description 'Specifies the command to be executed when the V… [See Man Page]'
complete -c i8kbuttons -s t -l timeout --description 'Specifies the interval in milliseconds at which… [See Man Page]'

