# i8kmon
# Autogenerated from man page /usr/share/man/man1/i8kmon.1.gz
# using Type1
complete -c i8kmon -s a -l auto --description 'Monitor cpu temperature and fan status and cont… [See Man Page]'
complete -c i8kmon -o na -l noauto --description 'Monitor cpu temperature and fan status but don\'… [See Man Page]'
complete -c i8kmon -s d -l daemon --description 'Run the program in daemon mode, i. e.'
complete -c i8kmon -o nd -l nodaemon --description 'Don\'t run the program in daemon mode, i. e.'
complete -c i8kmon -o nc -l nouserconfig --description 'Don\'t attempt to source the ~/.'
complete -c i8kmon -s v -l verbose --description 'Report hardware status and program actions on stdout.'
complete -c i8kmon -s g -l geometry --description 'Specifies the geometry of the applet window.'
complete -c i8kmon -s t -l timeout --description 'Specifies the interval at which the daemon chec… [See Man Page]'

