# id3info
# Autogenerated from man page /usr/share/man/man1/id3info.1.gz
# using Deroffing man parser
complete -c id3info -s h -l help --description 'Display help and exit.'
complete -c id3info -s v -l version --description 'Display version information and exit SEE ALSO i… [See Man Page]'

