# ifs
# Autogenerated from man page /usr/share/man/man6/ifs.6.gz
# using Deroffing man parser
complete -c ifs -o visual --description 'Specify which visual to use.'
complete -c ifs -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c ifs -o root --description 'Draw on the root window.'
complete -c ifs -o no-db --description 'Disable double-buffering.'
complete -c ifs -o delay --description 'Per-frame delay, in microseconds.   Default: 20000.'
complete -c ifs -o colors --description 'Number of colours to use.  Default: 200.'
complete -c ifs -o detail --description 'In -iterate mode, number of times to randomly i… [See Man Page]'
complete -c ifs -o functions --description 'Number of functions to be iterated.  Default: 3.'
complete -c ifs -o iterate --description 'Calculate by iteratively applying the functions… [See Man Page]'
complete -c ifs -o recurse --description 'Calculate by recursively applying all combinati… [See Man Page]'
complete -c ifs -o no-rotate --description 'Disable the rotation component of the functions.'
complete -c ifs -o no-scale --description 'Disable the scaling component of the functions.'
complete -c ifs -o no-translate --description 'Disable the varying translation component of the functions.'
complete -c ifs -o no-multi --description 'Turn off multi-coloured mode, only one colour i… [See Man Page]'
complete -c ifs -o 'iterate.' --description '.'
complete -c ifs -o fps --description 'Display the current frame rate and CPU load.'

