# imsmap
# Autogenerated from man page /usr/share/man/man6/imsmap.6.gz
# using Deroffing man parser
complete -c imsmap -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c imsmap -o root --description 'Draw on the root window.'
complete -c imsmap -o mono --description 'If on a color display, pretend we\'re on a monochrome display.'
complete -c imsmap -o install --description 'Install a private colormap for the window.'
complete -c imsmap -o visual --description 'Specify which visual to use.'
complete -c imsmap -o ncolors --description 'How many colors to use.   Default 50.'
complete -c imsmap -o delay --description 'How long to delay between images.   Default 10 seconds.'
complete -c imsmap -o delay2 --description 'How long to delay between bitmaps.   Default 200000 (0.'
complete -c imsmap -o iterations --description 'A measure of the resolution of the resultant im… [See Man Page]'
complete -c imsmap -o mode --description 'The axis upon which colors should be interpolat… [See Man Page]'
complete -c imsmap -o fps --description 'Display the current frame rate and CPU load.'

