# inotifywait
# Autogenerated from man page /usr/share/man/man1/inotifywait.1.gz
# using Deroffing man parser
complete -c inotifywait -s h -l help --description 'Output some helpful usage information.'
complete -c inotifywait -l fromfile --description 'Read filenames to watch or exclude from a file,… [See Man Page]'
complete -c inotifywait -s m -l monitor --description 'Instead of exiting after receiving a single eve… [See Man Page]'
complete -c inotifywait -s d -l daemon --description 'Same as --monitor, except run in the background… [See Man Page]'
complete -c inotifywait -s o -l outfile --description 'Output events to <file> rather than stdout.'
complete -c inotifywait -s s -l syslog --description 'Output errors to  syslog(3) system log module r… [See Man Page]'
complete -c inotifywait -s r -l recursive --description 'Watch all subdirectories of any directories pas… [See Man Page]'
complete -c inotifywait -s q -l quiet --description 'If specified once, the program will be less verbose.'
complete -c inotifywait -l exclude --description 'Do not process any events whose filename matche… [See Man Page]'
complete -c inotifywait -l excludei --description 'Do not process any events whose filename matche… [See Man Page]'
complete -c inotifywait -s t -l timeout --description 'Exit if an appropriate event has not occurred w… [See Man Page]'
complete -c inotifywait -s e -l event --description 'Listen for specific event(s) only.'
complete -c inotifywait -s c -l csv --description 'Output in CSV (comma-separated values) format.'
complete -c inotifywait -l timefmt --description 'Set a time format string as accepted by strftim… [See Man Page]'
complete -c inotifywait -l format --description 'Output in a user-specified format, using printf-like syntax.'

