# interaggregate
# Autogenerated from man page /usr/share/man/man6/interaggregate.6.gz
# using Deroffing man parser
complete -c interaggregate -o num-circles --description 'Number of slowly moving and growing discs to use.'
complete -c interaggregate -o growth-delay --description 'Delay in ms between drawing cycles.'
complete -c interaggregate -o fps --description 'Display the current frame rate and CPU load.'

