# loginctl
# Autogenerated from man page /usr/share/man/man1/loginctl.1.gz
# using Deroffing man parser
complete -c loginctl -s h -l help --description 'Prints a short help text and exits.'
complete -c loginctl -l version --description 'Prints a short version string and exits.'
complete -c loginctl -s p -l property --description 'When showing session/user/seat properties, limi… [See Man Page]'
complete -c loginctl -s a -l all --description 'When showing session/user/seat properties, show… [See Man Page]'
complete -c loginctl -s l -l full --description 'Do not ellipsize process tree entries.'
complete -c loginctl -l no-pager --description 'Do not pipe output into a pager.'
complete -c loginctl -l no-ask-password --description 'Do not query the user for authentication for pr… [See Man Page]'
complete -c loginctl -l kill-who --description 'When used with kill-session, choose which processes to kill.'
complete -c loginctl -s s -l signal --description 'When used with kill-session or kill-user, choos… [See Man Page]'
complete -c loginctl -s H -l host --description 'Execute operation remotely.'
complete -c loginctl -s P -l privileged --description 'Acquire privileges via PolicyKit before executi… [See Man Page]'
complete -c loginctl -l 'no-pager.' --description '.'

