# machinectl
# Autogenerated from man page /usr/share/man/man1/machinectl.1.gz
# using Deroffing man parser
complete -c machinectl -s h -l help --description 'Prints a short help text and exits.'
complete -c machinectl -l version --description 'Prints a short version string and exits.'
complete -c machinectl -s p -l property --description 'When showing machine properties, limit the outp… [See Man Page]'
complete -c machinectl -s a -l all --description 'When showing machine properties, show all prope… [See Man Page]'
complete -c machinectl -s l -l full --description 'Do not ellipsize process tree entries.'
complete -c machinectl -l no-pager --description 'Do not pipe output into a pager.'
complete -c machinectl -l no-ask-password --description 'Do not query the user for authentication for pr… [See Man Page]'
complete -c machinectl -l kill-who --description 'When used with kill-machine, choose which processes to kill.'
complete -c machinectl -s s -l signal --description 'When used with kill-machine, choose which signa… [See Man Page]'
complete -c machinectl -s H -l host --description 'Execute operation remotely.'
complete -c machinectl -s P -l privileged --description 'Acquire privileges via PolicyKit before executi… [See Man Page]'
complete -c machinectl -l 'no-pager.' --description '.'

