# maze
# Autogenerated from man page /usr/share/man/man6/maze.6.gz
# using Deroffing man parser
complete -c maze -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c maze -o root --description 'Draw on the root window.'
complete -c maze -o install --description 'Install a private colormap for the window.'
complete -c maze -o visual --description 'Specify which visual to use.'
complete -c maze -o grid-size --description 'The size of each block of the maze, in pixels; … [See Man Page]'
complete -c maze -o live-color --description 'The color of the path.'
complete -c maze -o dead-color --description 'The color of the failed path (it is also stippl… [See Man Page]'
complete -c maze -o skip-color --description 'The maze solver will choose to not go down a pa… [See Man Page]'
complete -c maze -o surround-color --description 'If the maze solver ever completely encloses an … [See Man Page]'
complete -c maze -o solve-delay --description 'Delay (in microseconds) between each step of the solution path.'
complete -c maze -o pre-delay --description 'Delay (in microseconds) between generating a ma… [See Man Page]'
complete -c maze -o post-delay --description 'Delay (in microseconds) after solving a maze an… [See Man Page]'
complete -c maze -o generator --description 'Sets the algorithm that will be used to generate the mazes.'
complete -c maze -o max-length --description 'Controls the maximum length of walls drawn in o… [See Man Page]'
complete -c maze -o fps --description 'Display the current frame rate and CPU load.'

