# mpc
# Autogenerated from man page /usr/share/man/man1/mpc.1.gz
# using Type1
complete -c mpc -s f -l format --description 'br Configure the format of song display for sta… [See Man Page]'
complete -c mpc -l wait --description 'br Wait for operation to finish (e. g.  database update).'
complete -c mpc -s q -l quiet -l no-status --description 'br Prevents the current song status from being … [See Man Page]'
complete -c mpc -s v -l verbose --description 'br Verbose output.'
complete -c mpc -s h -l host --description 'The host to connect to; if not given, the value… [See Man Page]'

