# mw-feedback
# Autogenerated from man page /usr/share/man/man8/mw-feedback.8.gz
# using Deroffing man parser
complete -c mw-feedback -l version --description 'show program\'s version number and exit.'
complete -c mw-feedback -s h -l help --description 'show this help message and exit AUTHOR MiserWare, Inc.'

