# ncmpcpp
# Autogenerated from man page /usr/share/man/man1/ncmpcpp.1.gz
# using Type1
complete -c ncmpcpp -s p -l port --description 'Connect to server at port [6600].'
complete -c ncmpcpp -s c -l config --description 'Use alternative configuration file.'
complete -c ncmpcpp -s s -l screen --description 'Specify the startup screen (<name> may be: help… [See Man Page]'
complete -c ncmpcpp -s '?' -l help --description 'Display help.'
complete -c ncmpcpp -s v -l version --description 'Display version information.'
complete -c ncmpcpp -l now-playing --description 'Display now playing song [{{(%l){{%a -%t}}|{%f}}].'

