# noof
# Autogenerated from man page /usr/share/man/man6/noof.6.gz
# using Deroffing man parser
complete -c noof -o visual --description 'Specify which visual to use.'
complete -c noof -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c noof -o root --description 'Draw on the root window.'
complete -c noof -o delay --description 'Per-frame delay, in microseconds.   Default: 10000 (0.'
complete -c noof -o fps --description 'Display the current frame rate, CPU load, and polygon count.'

