# noseguy
# Autogenerated from man page /usr/share/man/man6/noseguy.6.gz
# using Deroffing man parser
complete -c noseguy -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c noseguy -o root --description 'Draw on the root window.'
complete -c noseguy -o install --description 'Install a private colormap for the window.'
complete -c noseguy -o visual --description 'Specify which visual to use.'
complete -c noseguy -o font --description 'The font used for the messages.'
complete -c noseguy -o program --description 'This program will be run periodically, and its … [See Man Page]'
complete -c noseguy -o filename --description 'If mode is file, then the contents of this file… [See Man Page]'
complete -c noseguy -o text --description 'If mode is string, then this text will be used … [See Man Page]'
complete -c noseguy -o fps --description 'Display the current frame rate and CPU load.'

