# ntp-wait
# Autogenerated from man page /usr/share/man/man8/ntp-wait.8.gz
# using Deroffing man parser
complete -c ntp-wait -s n --description 'Number of tries before giving up.  The default is 1000.'
complete -c ntp-wait -s s --description 'Seconds to sleep between tries.  The default is 6 seconds.'
complete -c ntp-wait -s v --description 'Be verbose.'

