# ntptrace
# Autogenerated from man page /usr/share/man/man8/ntptrace.8.gz
# using Deroffing man parser
complete -c ntptrace -s n --description 'Turns off the printing of host names; instead, … [See Man Page]'

