# phosphor
# Autogenerated from man page /usr/share/man/man6/phosphor.6.gz
# using Deroffing man parser
complete -c phosphor -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c phosphor -o root --description 'Draw on the root window.'
complete -c phosphor -o install --description 'Install a private colormap for the window.'
complete -c phosphor -o visual --description 'Specify which visual to use.'
complete -c phosphor -o font --description 'The X font to use.'
complete -c phosphor -o scale --description 'How much to scale the font up: in other words, … [See Man Page]'
complete -c phosphor -o ticks --description 'The number of colors to use when fading to black.   Default 20.'
complete -c phosphor -o delay --description 'The speed of the terminal: how long to wait bet… [See Man Page]'
complete -c phosphor -o pty --description 'Launch the sub-program under a PTY, so that it … [See Man Page]'
complete -c phosphor -o pipe --description 'Launch the sub-program at the end of a pipe: do… [See Man Page]'
complete -c phosphor -o program --description 'The command to run to generate the text to display.'
complete -c phosphor -o esc --description 'When the user types a key with the Alt or Meta … [See Man Page]'
complete -c phosphor -o meta --description 'When Meta or Alt are held down, set the high bi… [See Man Page]'
complete -c phosphor -o del --description 'Swap Backspace and Delete.   This is the default.'
complete -c phosphor -o bs --description 'Do not swap Backspace and Delete.'
complete -c phosphor -o fps --description 'Display the current frame rate and CPU load.'

