# piecewise
# Autogenerated from man page /usr/share/man/man6/piecewise.6.gz
# using Deroffing man parser
complete -c piecewise -o visual --description 'Specify which visual to use.'
complete -c piecewise -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c piecewise -o root --description 'Draw on the root window.'
complete -c piecewise -o delay --description 'Per-frame delay, in microseconds.   Default: 5000 (0.'
complete -c piecewise -o count --description 'Number of circles.   Default: 32.'
complete -c piecewise -o ncolors --description 'Number of colors, only one of which is used at a time.'
complete -c piecewise -o colorspeed --description 'How fast the color changes (0 - 100).   Default: 10.'
complete -c piecewise -o minradius --description 'Minimum circle radius (as a proportion of screen height).'
complete -c piecewise -o maxradius --description 'Maximum circle radius (as a proportion of screen height).'
complete -c piecewise -o db -o no-db --description 'Whether to double buffer.'
complete -c piecewise -o fps --description 'Display the current frame rate and CPU load.'

