# polipo
# Autogenerated from man page /usr/share/man/man1/polipo.1.gz
# using Deroffing man parser
complete -c polipo -s h --description 'Display help and exit.'
complete -c polipo -s v --description 'Display the list of configuration variables and exit.'
complete -c polipo -s x --description 'Purge the on-disk cache and exit.'
complete -c polipo -s c --description 'Select an alternate configuration file.'

