# powertop
# Autogenerated from man page /usr/share/man/man8/powertop.8.gz
# using Deroffing man parser
complete -c powertop -l calibrate --description 'runs powertop in calibration mode.'
complete -c powertop -l 'csv[' --description 'generate a CSV report.'
complete -c powertop -l debug --description 'run in "debug" mode.'
complete -c powertop -l extech --description 'use the Extech Power Analyzer for measurements.'
complete -c powertop -l help --description 'show the help message.'
complete -c powertop -l 'html[' --description 'generate an HTML report.'
complete -c powertop -l 'iteration[' --description 'number of times to run each test.'
complete -c powertop -l quiet --description 'supress stderr output.'
complete -c powertop -l 'time[' --description 'generate a report for a specified number of seconds.'
complete -c powertop -l version --description 'print version information and exit.'

