# pwsafe
# Autogenerated from man page /usr/share/man/man1/pwsafe.1.gz
# using Type1
complete -c pwsafe -s f -l file --description 'Specify the database to manipulate.  Default is $HOME/. pwsafe.'
complete -c pwsafe -l dbversion --description 'Specify the database\'s version.  Default is 2.'
complete -c pwsafe -s I -l case --description 'REGEX is case-sensative.'
complete -c pwsafe -s l --description 'Show login and notes in list output.'
complete -c pwsafe -s u -l username --description 'Show username of listed account(s).'
complete -c pwsafe -s p -l password --description 'Show password of listed accounts(s).'
complete -c pwsafe -s E -l echo --description 'Force echo\'ing of entry to stdout.'
complete -c pwsafe -s o -l output --description 'Redirect username and password output to FILE.  Implies --echo.'
complete -c pwsafe -s x -l xclip --description 'Force copying of username and password to X clipboard.'
complete -c pwsafe -s d -l display --description 'Override $DISPLAY.  Implies --xclip.'
complete -c pwsafe -s s -l selection --description 'Select the X selection effected.'
complete -c pwsafe -s G -l ignore --description 'Add NAME to windows or hosts that do not receive the selection.'
complete -c pwsafe -s v -l verbose --description 'Print more information.'
complete -c pwsafe -s q -l quiet --description 'Print less information.'
complete -c pwsafe -s h -l help --description 'Show summary of options.'

