# pyro
# Autogenerated from man page /usr/share/man/man6/pyro.6.gz
# using Deroffing man parser
complete -c pyro -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c pyro -o root --description 'Draw on the root window.'
complete -c pyro -o mono --description 'If on a color display, pretend we\'re on a monochrome display.'
complete -c pyro -o install --description 'Install a private colormap for the window.'
complete -c pyro -o visual --description 'Specify which visual to use.'
complete -c pyro -o count --description 'How many particles should be allowed on the screen at once.'
complete -c pyro -o frequency --description 'How often new missiles should launch.   Default 30.'
complete -c pyro -o scatter --description 'How many particles should appear when a missile explodes.'
complete -c pyro -o fps --description 'Display the current frame rate and CPU load.'

