# rd-bomb
# Autogenerated from man page /usr/share/man/man6/rd-bomb.6.gz
# using Deroffing man parser
complete -c rd-bomb -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c rd-bomb -o root --description 'Draw on the root window.'
complete -c rd-bomb -o install --description 'Install a private colormap for the window.'
complete -c rd-bomb -o visual --description 'Specify which visual to use.'
complete -c rd-bomb -o height --description 'Specify the size of the tile, in pixels.'
complete -c rd-bomb -o diffusion --description 'These are constants in the equations that effec… [See Man Page]'
complete -c rd-bomb -o radius --description 'Size of the seed.'
complete -c rd-bomb -o size --description 'What fraction of the window is actively drawn, … [See Man Page]'
complete -c rd-bomb -o speed --description 'When a fraction of the screen is active, the ac… [See Man Page]'
complete -c rd-bomb -o delay --description 'How many milliseconds to delay between frames; … [See Man Page]'
complete -c rd-bomb -o width --description '.'
complete -c rd-bomb -o reaction --description '.'
complete -c rd-bomb -o fps --description 'Display the current frame rate and CPU load.'

