# saidar
# Autogenerated from man page /usr/share/man/man1/saidar.1.gz
# using Deroffing man parser
complete -c saidar -s d --description 'Wait DELAY seconds between updates (default 3).'
complete -c saidar -s c --description 'Enables coloured output.'
complete -c saidar -s v --description 'Prints the version number.'
complete -c saidar -s h --description 'Display help and exits COLOURED OUTPUT When the… [See Man Page]'

