# sensord
# Autogenerated from man page /usr/share/man/man8/sensord.8.gz
# using Deroffing man parser
complete -c sensord -s i -l interval --description 'Specify the interval between scanning for senso… [See Man Page]'
complete -c sensord -s l -l log-interval --description 'Specify the interval between logging all sensor… [See Man Page]'
complete -c sensord -s t -l rrd-interval --description 'Specify the interval between logging all sensor… [See Man Page]'
complete -c sensord -s T -l rrd-no-average --description 'Specify that the round-robin database should not be averaged.'
complete -c sensord -s r -l rrd-file --description 'Specify a round-robin database into which to lo… [See Man Page]'
complete -c sensord -s c -l config-file --description 'Specify a  libsensors (3) configuration file.'
complete -c sensord -s p -l pid-file --description 'Specify what PID file to write; the default is … [See Man Page]'
complete -c sensord -s f -l syslog-facility --description 'Specify the  syslog (3) facility to use when lo… [See Man Page]'
complete -c sensord -s g -l rrd-cgi --description 'Prints out a sample  rrdcgi (1) CGI script that… [See Man Page]'
complete -c sensord -s a -l load-average --description 'Include the load average in the RRD database.'
complete -c sensord -s d -l debug --description 'Prints a small amount of additional debugging information.'
complete -c sensord -s h -l help --description 'Prints a help message and exits.'
complete -c sensord -s v -l version --description 'Displays the program version and exits.'

