# slimlock
# Autogenerated from man page /usr/share/man/man1/slimlock.1.gz
# using Deroffing man parser
complete -c slimlock -s v --description 'display version information CONFIGURATION Sliml… [See Man Page]'

