# squiral
# Autogenerated from man page /usr/share/man/man6/squiral.6.gz
# using Deroffing man parser
complete -c squiral -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c squiral -o root --description 'Draw on the root window.'
complete -c squiral -o mono --description 'If on a color display, pretend we\'re on a monochrome display.'
complete -c squiral -o install --description 'Install a private colormap for the window.'
complete -c squiral -o visual --description 'Specify which visual to use.'
complete -c squiral -o fill --description 'Specify the percent (0-100) of the screen which… [See Man Page]'
complete -c squiral -o count --description 'The number of squiralies.'
complete -c squiral -o delay --description 'The wait between steps.   The default is 1000.'
complete -c squiral -o disorder --description 'The fraction of the time a squiraly will choose… [See Man Page]'
complete -c squiral -o handedness --description 'The fraction of the time a squiraly will choose… [See Man Page]'
complete -c squiral -o fps --description 'Display the current frame rate and CPU load.'

