# starwars
# Autogenerated from man page /usr/share/man/man6/starwars.6.gz
# using Deroffing man parser
complete -c starwars -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c starwars -o root --description 'Draw on the root window.'
complete -c starwars -o install --description 'Install a private colormap for the window.'
complete -c starwars -o visual --description 'Specify which visual to use.'
complete -c starwars -o program --description 'The command to run to generate the text to display.'
complete -c starwars -o size --description 'How large a font to use, in points.'
complete -c starwars -o columns --description 'How many columns of text should be visible on t… [See Man Page]'
complete -c starwars -o wrap --description 'Word-wrap lines when they reach the rightmost column.'
complete -c starwars -o no-wrap --description 'Do not word-wrap: just let the lines go off the… [See Man Page]'
complete -c starwars -o left -o center -o right --description 'Whether to align the text flush left, centered, or flush right.'
complete -c starwars -o lines --description 'How many lines should be allowed to be on the s… [See Man Page]'
complete -c starwars -o spin --description 'The star field on the background slowly rotates.'
complete -c starwars -o steps --description 'How many steps should be used to scroll a single line.'
complete -c starwars -o delay --description 'The delay between steps of the animation; defau… [See Man Page]'
complete -c starwars -o font --description 'The name of the font to use.'
complete -c starwars -o no-textures --description 'Instead of texture-mapping a real font to rende… [See Man Page]'
complete -c starwars -o no-smooth --description 'When using the line-segment font, turn off anti… [See Man Page]'
complete -c starwars -o no-thick --description 'When using the line-segment font, turn off use … [See Man Page]'
complete -c starwars -o fps --description 'Display the current frame rate, CPU load, and polygon count.'

