# starfish
# Autogenerated from man page /usr/share/man/man6/starfish.6.gz
# using Deroffing man parser
complete -c starfish -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c starfish -o root --description 'Draw on the root window.'
complete -c starfish -o mono --description 'If on a color display, pretend we\'re on a monochrome display.'
complete -c starfish -o install --description 'Install a private colormap for the window.'
complete -c starfish -o visual --description 'Specify which visual to use.'
complete -c starfish -o delay --description 'How much of a delay should be introduced betwee… [See Man Page]'
complete -c starfish -o thickness --description 'How wide each color band should be.'
complete -c starfish -o rotation --description 'How quickly the objects should rotate at each step.'
complete -c starfish -o colors --description 'How many colors to use.   Default 200.'
complete -c starfish -o duration --description 'How long to run before choosing a new shape.'
complete -c starfish -o delay2 --description 'When duration expires, how long to wait before … [See Man Page]'
complete -c starfish -o no-blob --description 'If blob option is specified, then the raw shape… [See Man Page]'
complete -c starfish -o blob --description '.'
complete -c starfish -o fps --description 'Display the current frame rate and CPU load.'

