# statgrab-make-mrtg-index
# Autogenerated from man page /usr/share/man/man1/statgrab-make-mrtg-index.1.gz
# using Deroffing man parser
complete -c statgrab-make-mrtg-index -l title --description 'Use TITLE as the title of the generated page.'
complete -c statgrab-make-mrtg-index -l help --description 'Display help and exit SEE ALSO statgrab(1) stat… [See Man Page]'

