# statgrab-make-mrtg-config
# Autogenerated from man page /usr/share/man/man1/statgrab-make-mrtg-config.1.gz
# using Deroffing man parser
complete -c statgrab-make-mrtg-config -l no-header --description 'Don\'t print MRTG global options; useful if you … [See Man Page]'
complete -c statgrab-make-mrtg-config -l workdir --description 'Use PATH for MRTG\'s WorkDir option.'
complete -c statgrab-make-mrtg-config -l statgrab --description 'Specify location of statgrab binary (default "statgrab").'
complete -c statgrab-make-mrtg-config -l help --description 'Display help and exit SEE ALSO statgrab(1) stat… [See Man Page]'

