# statgrab
# Autogenerated from man page /usr/share/man/man1/statgrab.1.gz
# using Deroffing man parser
complete -c statgrab -s l --description 'Linux sysctl-style output (default).'
complete -c statgrab -s b --description 'BSD sysctl-style output.'
complete -c statgrab -s m --description 'MRTG-compatible output.'
complete -c statgrab -s u --description 'Plain output (only show values).'
complete -c statgrab -s n --description 'Display cumulative stats once (default).'
complete -c statgrab -s s --description 'Display stat differences repeatedly.'
complete -c statgrab -s o --description 'Display stat differences once.'
complete -c statgrab -s t --description 'When repeating, wait DELAY seconds between updates (default 1).'
complete -c statgrab -s p --description 'Display CPU usage differences as percentages ra… [See Man Page]'
complete -c statgrab -s f --description 'Display floating-point values as integers scaled by FACTOR.'
complete -c statgrab -s K --description 'Display byte counts in kibibytes.'
complete -c statgrab -s M --description 'Display byte counts in mebibytes.'
complete -c statgrab -s G --description 'Display byte counts in gibibytes.'

