# systemd-udevd
# Autogenerated from man page /usr/share/man/man8/systemd-udevd.service.8.gz
# using Deroffing man parser
complete -c systemd-udevd -l daemon --description 'Detach and run in the background.'
complete -c systemd-udevd -l debug --description 'Print debug messages to stderr.'
complete -c systemd-udevd -l children-max --description 'Limit the number of events executed in parallel.'
complete -c systemd-udevd -l exec-delay --description 'Delay the execution of RUN instruction by the g… [See Man Page]'
complete -c systemd-udevd -l resolve-names --description 'Specify when systemd-udevd should resolve names… [See Man Page]'
complete -c systemd-udevd -l version --description 'Print version number.'
complete -c systemd-udevd -l help --description 'Print help text.'

