# systemd-run
# Autogenerated from man page /usr/share/man/man1/systemd-run.1.gz
# using Deroffing man parser
complete -c systemd-run -s h -l help --description 'Prints a short help text and exits.'
complete -c systemd-run -l version --description 'Prints a short version string and exits.'
complete -c systemd-run -l user --description 'Talk to the service manager of the calling user… [See Man Page]'
complete -c systemd-run -l scope --description 'Create a transient .'
complete -c systemd-run -l unit --description 'Use this unit name instead of an automatically generated one.'
complete -c systemd-run -l description --description 'Provide description for the unit.'
complete -c systemd-run -l slice --description 'Make the new . service or .'
complete -c systemd-run -l remain-after-exit --description 'After the service\\*(Aqs process has terminated,… [See Man Page]'
complete -c systemd-run -l send-sighup --description 'When terminating the scope unit, send a SIGHUP … [See Man Page]'

