# systemd-activate
# Autogenerated from man page /usr/share/man/man8/systemd-activate.8.gz
# using Deroffing man parser
complete -c systemd-activate -l help -s h --description 'Prints a short help text and exits.'
complete -c systemd-activate -l version --description 'Prints a short version string and exits.'
complete -c systemd-activate -s l -l listen --description 'Listen on this address.  Takes a string like "2000" or "127. 0.'
complete -c systemd-activate -s a -l accept --description 'Launch a separate instance of daemon per connec… [See Man Page]'
complete -c systemd-activate -s E -l environment --description 'Add this variable to the environment of the launched process.'

