# tangram
# Autogenerated from man page /usr/share/man/man6/tangram.6.gz
# using Deroffing man parser
complete -c tangram -o visual --description 'Specify which visual to use.'
complete -c tangram -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c tangram -o root --description 'Draw on the root window.'
complete -c tangram -o delay --description 'Per-frame delay, in microseconds.   Default: 10000 (0.'
complete -c tangram -o wireframe -o no-wireframe --description 'Render in wireframe instead of solid.'
complete -c tangram -o viewing_time --description 'Specify the length of time, in seconds, that th… [See Man Page]'
complete -c tangram -o rotate -o no-rotate --description 'Rotate the camera around the puzzle.'
complete -c tangram -o fps --description 'Display the current frame rate, CPU load, and polygon count.'

