# telinit
# Autogenerated from man page /usr/share/man/man8/telinit.8.gz
# using Deroffing man parser
complete -c telinit -l help --description 'Prints a short help text and exits.'
complete -c telinit -l no-wall --description 'Do not send wall message before reboot/halt/power-off.'

