# tickadj
# Autogenerated from man page /usr/share/man/man8/tickadj.8.gz
# using Deroffing man parser
complete -c tickadj -s a --description 'Set the kernel variable tickadj to the value tickadjspecified.'
complete -c tickadj -s A --description 'Set the kernel variable tickadj to an internall… [See Man Page]'
complete -c tickadj -s t --description 'Set the kernel variable tick to the value tick specified.'
complete -c tickadj -s s --description 'Set the kernel variable dosynctodr to zero, whi… [See Man Page]'
complete -c tickadj -s q --description 'Normally, tickadj is quite verbose about what it is doing.'

