# timetunnel
# Autogenerated from man page /usr/share/man/man6/timetunnel.6.gz
# using Deroffing man parser
complete -c timetunnel -o visual --description 'Specify which visual to use.'
complete -c timetunnel -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c timetunnel -o root --description 'Draw on the root window.'
complete -c timetunnel -o start --description 'Start time of loop, 0. 0 - 30. 00.  Default 0. 0.'
complete -c timetunnel -o end --description 'End time of loop, 0. 0 - 30. 00.  Default 27. 79.'
complete -c timetunnel -o dilate --description 'Scale time to speed or slow simulation.'
complete -c timetunnel -o no-logo --description 'Show only tunnels, no logos, etc.'
complete -c timetunnel -o reverse --description 'Play in reverse, including tunnels.'
complete -c timetunnel -o no-fog --description 'Turn off fog.'
complete -c timetunnel -o no-texture --description 'Turn off textures.'
complete -c timetunnel -o wireframe --description 'Show as wire frame.'
complete -c timetunnel -o fps -o no-fps --description 'Whether to show a frames-per-second display at … [See Man Page]'
complete -c timetunnel -o tardis --description 'Specify an xpm file to override default tardis texture.'
complete -c timetunnel -o head --description 'Specify an xpm file to override default Dr.  Who head texture.'
complete -c timetunnel -o marquee --description 'Specify an xpm file to override default show marquee texture.'
complete -c timetunnel -o tun1 --description 'Specify an xpm file to override default tardis tunnel texture.'
complete -c timetunnel -o tun2 --description 'Specify an xpm file to override default middle tunnel texture.'
complete -c timetunnel -o tun3 --description 'Specify an xpm file to override default final tunnel texture.'

