# tsocks
# Autogenerated from man page /usr/share/man/man8/tsocks.8.gz
# using Deroffing man parser
complete -c tsocks -l disable-debug --description 'some problems with programs that redirect standard error.'

