# vidwhacker
# Autogenerated from man page /usr/share/man/man6/vidwhacker.6.gz
# using Deroffing man parser
complete -c vidwhacker -o root --description 'Draw on the root window.   This is the default.'
complete -c vidwhacker -o verbose --description 'Print diagnostics.'
complete -c vidwhacker -o stdin --description 'Instead of grabbing an image from disk or video… [See Man Page]'
complete -c vidwhacker -o delay --description 'How long to sleep between images.'
complete -c vidwhacker -o stdout --description 'Instead of displaying the image on a window or … [See Man Page]'
complete -c vidwhacker -o directory --description 'Use this directory instead of the imageDirector… [See Man Page]'
complete -c vidwhacker -o fps --description 'Display the current frame rate and CPU load.'

