# vifm
# Autogenerated from man page /usr/share/man/man1/vifm.1.gz
# using Deroffing man parser
complete -c vifm -s f --description 'only used from the vifm. vim script.'
complete -c vifm -l logging --description 'Log some errors to $VIFM/log.'
complete -c vifm -l remote --description 'Sends the rest of command line to the active vi… [See Man Page]'
complete -c vifm -s c --description 'Run command-line mode <command> on startup.'
complete -c vifm -l help -s h --description 'Show an overview of the commandline options.'
complete -c vifm -l version -s v --description 'Show version information and quit.'
complete -c vifm -l no-configs --description 'Don\'t read vifmrc and vifminfo.'
complete -c vifm -l --- --description '.'
complete -c vifm -l ---- --description '.'
complete -c vifm -l ------------ --description '.'
complete -c vifm -l ------------------ --description '.'
complete -c vifm -l ----------- --description '.'

