# webcollage
# Autogenerated from man page /usr/share/man/man6/webcollage.6.gz
# using Deroffing man parser
complete -c webcollage -o root --description 'Draw on the root window.'
complete -c webcollage -o window-id --description 'Draw to the indicated window instead; this only… [See Man Page]'
complete -c webcollage -o verbose -s v --description 'Print diagnostics to stderr.'
complete -c webcollage -o timeout --description 'How long to wait for a URL to complete before g… [See Man Page]'
complete -c webcollage -o delay --description 'How long to sleep between images.   Default 2 seconds.'
complete -c webcollage -o background --description 'What to use for the background onto which images are pasted.'
complete -c webcollage -o size --description 'Normally, the output image will be made to be t… [See Man Page]'
complete -c webcollage -o opacity --description 'How transparently to paste the images together, with 0.'
complete -c webcollage -o no-output --description 'If this option is specified, then no composite … [See Man Page]'
complete -c webcollage -o urls-only --description 'If this option is specified, then no composite … [See Man Page]'
complete -c webcollage -o imagemap --description 'If this option is specified, then instead of wr… [See Man Page]'
complete -c webcollage -o filter --description 'Filter all source images through this command.'
complete -c webcollage -o filter2 --description 'Filter the composite image through this command.'
complete -c webcollage -o http-proxy --description 'If you must go through a proxy to connect to th… [See Man Page]'
complete -c webcollage -o dictionary --description 'Webcollage normally looks at the system\'s defau… [See Man Page]'
complete -c webcollage -o driftnet --description 'driftnet (1) is a program that snoops your loca… [See Man Page]'
complete -c webcollage -o directory --description 'Instead of searching the web for images, use th… [See Man Page]'
complete -c webcollage -o extra -o 'args\'' --description '.'
complete -c webcollage -o fps --description 'Display the current frame rate and CPU load (MacOS only).'

