# xspirograph
# Autogenerated from man page /usr/share/man/man6/xspirograph.6.gz
# using Deroffing man parser
complete -c xspirograph -o window --description 'Draw on a newly-created window.   This is the default.'
complete -c xspirograph -o root --description 'Draw on the root window.'
complete -c xspirograph -o install --description 'Install a private colormap for the window.'
complete -c xspirograph -o visual --description 'Specify which visual to use.'
complete -c xspirograph -o delay --description 'The delay between finishing one draw and starting the next.'
complete -c xspirograph -o subdelay --description 'The time to delay between each hundred line draws.'
complete -c xspirograph -o alwaysfinish -o noalwaysfinish --description 'If you want each pattern to draw until it is do… [See Man Page]'
complete -c xspirograph -o layers --description 'Number of pairs of patterns to draw between each erase.'

