#!/bin/bash

# this is a simple config for herbstluftwm

hc() {
    herbstclient "$@"
}

hc emit_hook reload

# remove all existing keybindings
hc keyunbind --all

# keybindings
Mod=Mod4   # Use the super key as the main modifier

hc keybind $Mod-Shift-c quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-Shift-q close

# basic movement
# focusing clients
hc keybind $Mod-h     focus left
hc keybind $Mod-j     focus down
hc keybind $Mod-k     focus up
hc keybind $Mod-l     focus right

# moving clients
hc keybind $Mod-Shift-h     shift left
hc keybind $Mod-Shift-j     shift down
hc keybind $Mod-Shift-k     shift up
hc keybind $Mod-Shift-l     shift right

# splitting frames
# create an empty frame at the specified direction
hc keybind $Mod-v       split bottom 0.5
hc keybind $Mod-b       split right 0.5

# let the current frame explode into subframes
hc keybind $Mod-Control-space split explode

# resizing frames
resizestep=0.05
hc keybind $Mod-Control-h       resize left +$resizestep
hc keybind $Mod-Control-j       resize down +$resizestep
hc keybind $Mod-Control-k       resize up +$resizestep
hc keybind $Mod-Control-l       resize right +$resizestep

# tag_names=( 0001 0010 0011 0100 0101 1010 1011 1100 1101 1110 )
# tag_names=( α β γ δ ε ζ η θ ι κ )
tag_names=( {1..5} )
tag_keys=( {1..5} )

hc rename default "${tag_names[0]}" || true
for i in ${!tag_names[@]} ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# cycle through tags
hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma  use_index -1 --skip-visible

# layouting
hc keybind $Mod-q remove
hc keybind $Mod-space cycle_layout 1
hc keybind $Mod-s floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-t pseudotile toggle

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# focus
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-c cycle
hc keybind $Mod-i jumpto urgent

# theme
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_active_color '#f92672'
hc set frame_border_normal_color '#272822'
hc set frame_bg_normal_color '#383830'
hc set frame_bg_active_color '#383830'
1c set frame_border_width 0
hc set always_show_frame 0
hc set frame_bg_transparent 1
hc set frame_transparent_width 0
hc set frame_gap 10

bw=1
tw=1
hc set_attr theme.tiling.active.border_width $bw
hc set_attr theme.tiling.active.padding_top $tw
hc set_attr theme.tiling.active.color '#f92672'
hc set_attr theme.tiling.normal.border_width $bw
hc set_attr theme.tiling.normal.padding_top $tw
hc set_attr theme.tiling.normal.color '#383830'
hc set_attr theme.tiling.urgent.border_width $bw
hc set_attr theme.tiling.urgent.padding_top $tw
hc set_attr theme.tiling.urgent.color '#272822'

hc set_attr theme.floating.active.border_width 1
hc set_attr theme.floating.normal.border_width 1
hc set_attr theme.floating.urgent.border_width 1
hc set_attr theme.floating.active.color '#f92672'
hc set_attr theme.floating.normal.color '#272822'
hc set_attr theme.floating.urgent.color '#272822'
hc set window_gap 5
hc set frame_padding 0
5c set smart_window_surroundings 0
hc set smart_frame_surroundings 1
hc set mouse_recenter_gap 0

# rules
hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
# hc rule focus=off # normally do not focus new clients
# give focus to most common terminals
# hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on


# unlock, just to be sure
hc unlock

herbstclient set tree_style '╾│ ├└╼─┐'

# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:
hc detect_monitors

# find the panel
panel=/home/niklas/.config/herbstluftwm/panel
[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel
for monitor in $(herbstclient list_monitors | cut -d: -f1) ; do
    # start it on each monitor
    "$panel" $monitor &
done
