history-length: 1000
ignore-submodules:
- ~/.rvm
repositories:
- ~/documents/projects/G:
    remotes:
    - origin: git@github.com/kokakolako/G.git
submodules:
- /home/niklas/.zprezto:
    ignore_dirty: true
- /home/niklas/.config/vim/plugins/YouCompleteMe/third_party/ycmd/third_party/OmniSharpServer:
    ignore_dirty: true
